kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: jason1992/zeppelin:latest
          env:
          - name: SPARK_SERVICE_NAME
            value: "spark-master"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi


