---
apiVersion: v1
kind: Service
metadata:
  name: kafka-server
  namespace: default
spec:
  ports:
  - port: 29091
    nodePort: 30001
    name: port0
  type: NodePort
  selector:
    app: kafka-server
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: broker
  namespace: default
spec:
  serviceName: "kafka-server"
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka-server
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka-server
        image: confluentinc/cp-kafka:latest
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:32181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://broker-0.kafka-server.default.svc.cluster.local:20901
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "2"
        ports:
        - containerPort: 20901
        - containerPort: 20902
